---
abstract: 'A ZeroMQ2 wrapper for Perl'
author:
  - 'Steffen Mueller, E<lt>smueller@cpan.orgE<gt>'
build_requires:
  ExtUtils::Typemap::ObjectMap: 0.01
  ExtUtils::XSpp: 0.12
  ExtUtils::XSpp::Plugin::Cloning: 0.01
configure_requires:
  ExtUtils::Constant: 0
  ExtUtils::CppGuess: 0.04
  Module::Build: 0.36
  Module::Build::WithXSpp: 0.05
generated_by: 'Module::Build version 0.3605'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ZeroMQ
provides:
  ZeroMQ:
    file: lib/ZeroMQ.pm
    version: 0.01
requires:
  ExtUtils::XSpp: 0.12
  ExtUtils::XSpp::Plugin::Cloning: 0.01
  Storable: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
